services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - faces_data:/tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:80'

volumes:
  db_data:
  faces_data:
